"use client"

import { useState, useEffect } from 'react'
import { View } from '../../lib/types'
import { getEvaluation, StudentProfileForAI, AIEvaluation } from '../../lib/api'
import { Icon } from '../icons/Icon'

interface EvaluationScreenProps {
  studentProfile: StudentProfileForAI
  onViewChange: (view: View) => void
}

export function EvaluationScreen({ studentProfile, onViewChange }: EvaluationScreenProps) {
  const [evaluation, setEvaluation] = useState<AIEvaluation | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getEvaluation(studentProfile).then(result => {
      setEvaluation(result)
      setLoading(false)
    })
  }, [])

  const levelColor = (level: string) => {
    switch (level) {
      case 'strong': return 'var(--success)'
      case 'developing': return 'var(--primary)'
      case 'needs_work': return 'var(--warning, #f59e0b)'
      default: return 'var(--muted)'
    }
  }

  const levelLabel = (level: string) => {
    switch (level) {
      case 'strong': return 'Strong'
      case 'developing': return 'Developing'
      case 'needs_work': return 'Needs work'
      default: return level
    }
  }

  return (
    <main className="page-shell">
      <div className="evaluation-layout">
        {/* Back link */}
        <button className="btn-text" onClick={() => onViewChange('progress')}>
          <Icon type="arrow-left" size={14} /> Back to progress
        </button>

        {/* Header */}
        <div className="evaluation-header">
          <p className="eyebrow">
            <Icon type="brain" size={12} />
            AI-Powered Analysis
          </p>
          <h1>Your <span>evaluation</span></h1>
          <p>A personalized assessment of your understanding of DC circuits, generated by the AI tutor.</p>
        </div>

        {loading ? (
          <div style={{ display: 'grid', gap: '12px' }}>
            <div className="skeleton skeleton-card" />
            <div className="skeleton skeleton-card" />
            <div className="skeleton skeleton-text" />
            <div className="skeleton skeleton-text" />
            <div className="skeleton skeleton-card" />
          </div>
        ) : !evaluation ? (
          <div className="empty-state">
            <div className="empty-state-icon">
              <Icon type="brain" size={32} />
            </div>
            <h2>Not enough data yet</h2>
            <p>Make some predictions in the lab to get a personalized AI evaluation of your understanding.</p>
            <button className="btn btn-primary" onClick={() => onViewChange('simulate')}>
              Go to lab
            </button>
          </div>
        ) : (
          <>
            {/* AI badge */}
            {evaluation.isAI && (
              <div className="eval-ai-badge">
                <Icon type="sparkles" size={12} />
                <span>Generated by AI Tutor</span>
              </div>
            )}

            {/* Overall Assessment */}
            <div className="eval-section eval-assessment">
              <div className="eval-section-label">
                <Icon type="brain" size={14} />
                Overall Assessment
              </div>
              <p className="eval-assessment-text">{evaluation.overallAssessment}</p>
            </div>

            {/* Concept Analysis */}
            {evaluation.conceptAnalysis.length > 0 && (
              <div className="eval-section">
                <div className="eval-section-label">
                  <Icon type="lightbulb" size={14} />
                  Concept Analysis
                </div>
                <div className="eval-concepts">
                  {evaluation.conceptAnalysis.map((c, i) => (
                    <div key={i} className="eval-concept-card">
                      <div className="eval-concept-header">
                        <span className="eval-concept-name">{c.concept}</span>
                        <span
                          className="eval-concept-level"
                          style={{ background: levelColor(c.level), color: 'white' }}
                        >
                          {levelLabel(c.level)}
                        </span>
                      </div>
                      <p className="eval-concept-analysis">{c.analysis}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Misconceptions */}
            {evaluation.misconceptions.length > 0 && (
              <div className="eval-section">
                <div className="eval-section-label">
                  <Icon type="alert-triangle" size={14} />
                  Diagnosed Misconceptions
                </div>
                <div className="eval-misconceptions">
                  {evaluation.misconceptions.map((m, i) => (
                    <div key={i} className="eval-misconception-card">
                      <div className="eval-misconception-label">{m.label}</div>
                      <p className="eval-misconception-explanation">{m.explanation}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Recommendations */}
            {evaluation.recommendations.length > 0 && (
              <div className="eval-section">
                <div className="eval-section-label">
                  <Icon type="target" size={14} />
                  Recommendations
                </div>
                <ul className="eval-recommendations">
                  {evaluation.recommendations.map((r, i) => (
                    <li key={i} className="eval-recommendation-item">
                      <span className="eval-rec-number">{i + 1}</span>
                      <span>{r}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Encouragement */}
            {evaluation.encouragement && (
              <div className="eval-encouragement">
                <Icon type="sparkles" size={16} />
                <p>{evaluation.encouragement}</p>
              </div>
            )}

            {/* Actions */}
            <div className="eval-actions">
              <button className="btn btn-primary" onClick={() => onViewChange('simulate')}>
                Back to lab
              </button>
              <button className="btn btn-outline" onClick={() => onViewChange('progress')}>
                View progress
              </button>
            </div>
          </>
        )}
      </div>
    </main>
  )
}
